//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FencingScrapper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comany
    {
        public int ComanyID { get; set; }
        public string CompanyName { get; set; }
        public string Email { get; set; }
        public string State { get; set; }
        public string ComanyURL { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
